# Generated by Django 4.1.7 on 2023-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("pass1", models.CharField(max_length=128)),
                ("gender", models.CharField(max_length=10)),
                ("tel", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
